### ISSUE TITLE
How hard was it to develop?

### ISSUE THREAD

**Issue by kvnandula04** [fsacer/FailLang#10]
Hi @fsacer,

I am actually working on my own dialect of Lox at the moment and I'm thinking about implementing the tree-walk interpreter. So far, there are some blanks in my head with some of the code involved. I was wondering how hard was it to implement Lox? Did you understand the book? And how difficult was it to add your own features?

Any responses would be much appreciated!

**Comment by fsacer** [comment]
Hey @kvnandula04 sorry for late reply, that sounds like a cool idea. Implementing Lox was pretty easy, as I pretty much followed the book Crafting Interpreters chapter by chapter and used most of the code that was already there. The book was easily understandable had a really good structure to describe the topics, adding my own features was harder, but you can look at how other interpreters implemented it, also on Bob's repo there are some answers for implementing the questions that the author asked.
